### ISSUE TITLE
Implement motor controls in the firmware

### ISSUE THREAD

**Issue by eeshiken** [attackle/rembot#1]
Implement the motor controls so that the motors move in a line to any coordinate they are passed. This means that all motors have to move simultaneously. 

Example moving effector from 0,0 to 5,5 should be a 45-degree line.

**Comment by eeshiken** [comment]
We probably dont need accelerations in this case

**Comment by elviseshikena** [comment]
Have to fix firmware stepper control method. Current method doesn't work from tests conducted on `March  8, 2018`

**Comment by elviseshikena** [comment]
Issue closing due to project discontinuity
