### ISSUE TITLE
Write algorithm to scale image to landscape a4 paper

### ISSUE THREAD

**Issue by eeshiken** [attackle/rembot#10]
- [ ] Scale image img-width to paper-width: if img-width > img-height
- [ ] Scale image height to paper-height : if img-width< img-height

## Resources
[Image scaling](https://docs.opencv.org/3.4.0/da/d6e/tutorial_py_geometric_transformations.html)

**Comment by elviseshikena** [comment]
Issue closing due to project disconitnuity
