### ISSUE TITLE
Create GCODE generator CLI

### ISSUE THREAD

**Issue by eeshiken** [attackle/rembot#13]
A GCODE generator command line tool that you could pass it an image and produce a file of a list of commands such as below:

This example file contains codes to draw a boundary square of 100pixels
```
R0 
G0
G2 P1 
G1 X100 Y0 F500
G1 X100 Y100 F500
G1 X0 Y100 F500
G1 X0 Y0 F500
G2 P0
R1
```

Interpretation
```
;Start
;Rapid Reset to switches origin 0,0
;Drop pen
;Move to 100,0
;Move to 100,100
;Move to 0,100
;Move to 0,0
;Lift pen
;End
```

**Comment by yasster** [comment]
@eeshiken This doesn't change anything! I have a couple ones locally but its the implementation of the GCODE in the Arduino that matters. The GCODE needs to be rewritten in order to prepare an algorithm for it.

**Comment by eeshiken** [comment]
I think the description is a bit clearer let me know if it is not

**Comment by eeshiken** [comment]
Implemented a script which is good for application. File can be found in `interface/test/gcode-generator.py`. This uses lessons and code from `dmap2png`, a depth mapping milling tool.
